name: Use Secrets Example

on: [push]  # 또는 원하는 트리거 이벤트를 설정하세요

jobs:
  use-secrets:
    runs-on: ubuntu-latest
    environment: your_environment_name  # GitHub에서 설정한 환경 이름

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 원하는 Python 버전을 지정하세요

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install anthropic openai  # 필요한 라이브러리를 설치하세요

    - name: Run script with secrets
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
      run: |
        python basic pipeline hybrid.py  # 실행할 Python 스크립트 이름
